<section id="section-a"> 
<p>Hesed foods is that one place you will find vegetables and fruits fresh from kenyan farms</p>
 </section>
 <section id="section-b">
<p>We also offer delivery to at a low fee to your house.Our team is very competent in making you a satisfied customer.</p>
 </section>
 <section id="section-c">
<div class="box-1">
<img src="('../IMG/fruits.jpg')">
</div>
<div class="box-2">
<img src="('../IMG/vegetables.jpg')">
</div>
<div class="box-3">
<img src="('../IMG/grains.jpg')">
</div>
 </section>
